export const GET_DASHBOARD_DATA_REQUEST = "GET_DASHBOARD_DATA_REQUEST";
export const GET_DASHBOARD_DATA_SUCCESS = "GET_DASHBOARD_DATA_SUCCESS";
export const GET_DASHBOARD_DATA_FAILURE = "GET_DASHBOARD_DATA_FAILURE";

export const DELETE_DASHBOARD_REQUEST = "DELETE_DASHBOARD_REQUEST";
export const DELETE_DASHBOARD_SUCCESS = "DELETE_DASHBOARD_SUCCESS";
export const DELETE_DASHBOARD_FAILURE = "DELETE_DASHBOARD_FAILURE";

export const ADD_NEW_DASHBOARD_DATA_REQUEST = "ADD_NEW_DASHBOARD_DATA_REQUEST";
export const ADD_NEW_DASHBOARD_DATA_SUCCESS = "ADD_NEW_DASHBOARD_DATA_SUCCESS";
export const ADD_NEW_DASHBOARD_DATA_FAILURE = "ADD_NEW_DASHBOARD_DATA_FAILURE";

export const UPDATE_DASHBOARD_DATA_REQUEST = "UPDATE_DASHBOARD_DATA_REQUEST";
export const UPDATE_DASHBOARD_DATA_SUCCESS = "UPDATE_DASHBOARD_DATA_SUCCESS";
export const UPDATE_DASHBOARD_DATA_FAILURE = "UPDATE_DASHBOARD_DATA_FAILURE";

export const GET_DASHBOARD_BYID_REQUEST = "GET_DASHBOARD_BYID_REQUEST";
export const GET_DASHBOARD_BYID_SUCCESS = "GET_DASHBOARD_BYID_SUCCESS";
export const GET_DASHBOARD_BYID_ERROR = "GET_DASHBOARD_BYID_ERROR";
